"""empty message

Revision ID: cf5645d8355f
Revises: 
Create Date: 2020-06-03 16:02:25.358381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5645d8355f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selected_answers', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('selected_answers_user_id_fkey', 'selected_answers', type_='foreignkey')
    op.create_foreign_key(None, 'selected_answers', 'questions', ['question_id'], ['id'])
    op.drop_column('selected_answers', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selected_answers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'selected_answers', type_='foreignkey')
    op.create_foreign_key('selected_answers_user_id_fkey', 'selected_answers', 'users', ['user_id'], ['id'])
    op.drop_column('selected_answers', 'question_id')
    # ### end Alembic commands ###
